//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcProject.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header1.
        /// </summary>
        public static string blockMenuHeader1 {
            get {
                return ResourceManager.GetString("blockMenuHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header2.
        /// </summary>
        public static string blockMenuHeader2 {
            get {
                return ResourceManager.GetString("blockMenuHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header3.
        /// </summary>
        public static string blockMenuHeader3 {
            get {
                return ResourceManager.GetString("blockMenuHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header4.
        /// </summary>
        public static string blockMenuHeader4 {
            get {
                return ResourceManager.GetString("blockMenuHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header5.
        /// </summary>
        public static string blockMenuHeader5 {
            get {
                return ResourceManager.GetString("blockMenuHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header6.
        /// </summary>
        public static string blockMenuHeader6 {
            get {
                return ResourceManager.GetString("blockMenuHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrary to popular belief, Lorem Ipsum is not simply random tex.
        /// </summary>
        public static string blockMenuParagraph1 {
            get {
                return ResourceManager.GetString("blockMenuParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
        /// </summary>
        public static string blockMenuParagraph2 {
            get {
                return ResourceManager.GetString("blockMenuParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.
        /// </summary>
        public static string blockMenuParagraph3 {
            get {
                return ResourceManager.GetString("blockMenuParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC.
        /// </summary>
        public static string blockMenuParagraph4 {
            get {
                return ResourceManager.GetString("blockMenuParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is a treatise on the theory of ethics, very popular during the Renaissance.
        /// </summary>
        public static string blockMenuParagraph5 {
            get {
                return ResourceManager.GetString("blockMenuParagraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32.
        /// </summary>
        public static string blockMenuParagraph6 {
            get {
                return ResourceManager.GetString("blockMenuParagraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s.
        /// </summary>
        public static string carouselHeaderTxt1 {
            get {
                return ResourceManager.GetString("carouselHeaderTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        /// </summary>
        public static string carouselHeaderTxt2 {
            get {
                return ResourceManager.GetString("carouselHeaderTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        /// </summary>
        public static string carouselHeaderTxt3 {
            get {
                return ResourceManager.GetString("carouselHeaderTxt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as opposed to using &apos;Content here, content here&apos;, making it look like readable English.
        /// </summary>
        public static string carouselpTxt1 {
            get {
                return ResourceManager.GetString("carouselpTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.
        /// </summary>
        public static string carouselpTxt2 {
            get {
                return ResourceManager.GetString("carouselpTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
        /// </summary>
        public static string carouselpTxt3 {
            get {
                return ResourceManager.GetString("carouselpTxt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu1.
        /// </summary>
        public static string navMenuItem1 {
            get {
                return ResourceManager.GetString("navMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu2.
        /// </summary>
        public static string navMenuItem2 {
            get {
                return ResourceManager.GetString("navMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu3.
        /// </summary>
        public static string navMenuItem3 {
            get {
                return ResourceManager.GetString("navMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu4.
        /// </summary>
        public static string navMenuItem4 {
            get {
                return ResourceManager.GetString("navMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is text 1.
        /// </summary>
        public static string text1 {
            get {
                return ResourceManager.GetString("text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
    }
}
